In [17]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [18]:
# Create character sequence: A to Z
sequence = list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

print(sequence)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']


In [19]:
# Define window size: 3 characters → 1 output
window_size = 3

# X = input characters
# y = next character
X = []
y = []

In [20]:
# Create input-output pairs
for i in range(len(sequence) - window_size):
    X.append(sequence[i:i + window_size])
    y.append(sequence[i + window_size])

print("First 5 input examples:")
print(X[:5])

print("First 5 answers:")
print(y[:5])

First 5 input examples:
[['A', 'B', 'C'], ['B', 'C', 'D'], ['C', 'D', 'E'], ['D', 'E', 'F'], ['E', 'F', 'G']]
First 5 answers:
['D', 'E', 'F', 'G', 'H']


In [21]:
# Create character-to-number mapping
chars = sorted(set(sequence))

char_to_number = {
    char: i for i, char in enumerate(chars)
}

number_to_char = {
    i: char for char, i in char_to_number.items()
}

print("Character to number:")
print(char_to_number)

Character to number:
{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19, 'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 'Z': 25}


In [22]:
# Convert X characters to numbers
X = np.array([
    [char_to_number[char] for char in row]
    for row in X
])

# Convert y characters to numbers
y = np.array([
    char_to_number[char]
    for char in y
])

print("X:")
print(X[:5])

print("y:")
print(y[:5])

X:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
y:
[3 4 5 6 7]


In [23]:
# Reshape X to: samples, timesteps, features
X = X.reshape((X.shape[0], X.shape[1], 1))

print("New X shape:", X.shape)

New X shape: (23, 3, 1)


In [24]:
model = Sequential()

model.add(
    SimpleRNN(
        50,
        activation='relu',
        input_shape=(window_size, 1)
    )
)

model.add(
    Dense(len(chars), activation='softmax')
)

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 50)             │         2,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 26)             │         1,326 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,926 (15.34 KB)

 Trainable params: 3,926 (15.34 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [26]:
model.fit(
    X,
    y,
    epochs=500,
    verbose=2
)

print("Training complete.")

Epoch 1/500
1/1 - 1s - 1s/step - accuracy: 0.0435 - loss: 5.2684
Epoch 2/500
1/1 - 0s - 52ms/step - accuracy: 0.0435 - loss: 5.0365
Epoch 3/500
1/1 - 0s - 52ms/step - accuracy: 0.0435 - loss: 4.8204
Epoch 4/500
1/1 - 0s - 51ms/step - accuracy: 0.0435 - loss: 4.6217
Epoch 5/500
1/1 - 0s - 43ms/step - accuracy: 0.0435 - loss: 4.4421
Epoch 6/500
1/1 - 0s - 45ms/step - accuracy: 0.0435 - loss: 4.2811
Epoch 7/500
1/1 - 0s - 48ms/step - accuracy: 0.0435 - loss: 4.1394
Epoch 8/500
1/1 - 0s - 45ms/step - accuracy: 0.0435 - loss: 4.0140
Epoch 9/500
1/1 - 0s - 50ms/step - accuracy: 0.0435 - loss: 3.9016
Epoch 10/500
1/1 - 0s - 49ms/step - accuracy: 0.0870 - loss: 3.8036
Epoch 11/500
1/1 - 0s - 42ms/step - accuracy: 0.0435 - loss: 3.7197
Epoch 12/500
1/1 - 0s - 45ms/step - accuracy: 0.0435 - loss: 3.6466
Epoch 13/500
1/1 - 0s - 42ms/step - accuracy: 0.0435 - loss: 3.5853
Epoch 14/500
1/1 - 0s - 45ms/step - accuracy: 0.0435 - loss: 3.5329
Epoch 15/500
1/1 - 0s - 45ms/step - accuracy: 0.0435 - loss

In [29]:
# Give a new input
test_input = ['A', 'B', 'C']

# Convert characters to numbers
test_input = np.array([
    char_to_number[char]
    for char in test_input
])

# RNN expects:
# samples, timesteps, features
test_input = test_input.reshape(
    (1, window_size, 1)
)

# Predict
predicted = model.predict(
    test_input,
    verbose=0
)

# Get character with highest probability
predicted_index = np.argmax(predicted[0])

# Convert number back to character
predicted_char = number_to_char[predicted_index]

print("Input:", ['A', 'B', 'C'])
print("Predicted next character:", predicted_char)

Input: ['a', 'b', 'c']
Predicted next character: D


In [30]:
test_input = ['A', 'B', 'C']

test_input = np.array([
    char_to_number[char]
    for char in test_input
])

test_input = test_input.reshape(
    (1, window_size, 1)
)

predicted = model.predict(
    test_input,
    verbose=0
)

predicted_index = np.argmax(predicted[0])

predicted_char = number_to_char[predicted_index]

print("Input:", ['A', 'B', 'C'])
print("Predicted next character:", predicted_char)

Input: ['A', 'B', 'C']
Predicted next character: D
